version: 2
updates:

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  labels:
  - dependencies
  - github-actions
  reviewers:
  - nebhale

- package-ecosystem: cargo
  directory: /
  schedule:
    interval: daily
  labels:
  - dependencies
  - cargo
  reviewers:
  - nebhale
